### ISSUE TITLE
blender?

### ISSUE THREAD

**Issue by j2l** [mpreble/UnityFBXImporter#3]
What is needed to adapt it to blender 6.1 ASCII?

**Comment by mpreble** [comment]
I'm not entirely sure, for 2 reasons:

1) I've not touched this code in years, so I myself am a bit out of the loop on it....

2) I'm unsure of Blender's FBX format. They were (are) likely using a different version than Autodesk was (is).

What you can do is take a look through a saved out fbx from blender. Find out where things like vertices, normals, etc are saved out & what their format is. My guess is either the object grouping or the data format is slightly different. So functions for retrieving normals etc will either need to parse for a different format, or parse in a different part of the file. Again I've not looked at Blender's FBX exports so I'm not sure what this looks like.

**Comment by j2l** [comment]
Thanks for this fast reply. I understand your point. 
I think it's a [long waited](http://forum.unity3d.com/threads/fbx-mesh-importer-at-runtime.230787/) function and it seems that someone with good blender knowledge could adapt [this](https://github.com/iamsed/blendToFbxExporterForUnity) pretty fast. I'm not, unfortunately.

**Comment by mpreble** [comment]
I may actually be revisiting this project in the (relatively) near future. So as to not get hopes up, it would still be a couple months at the very least. Work + side coding is....difficult for me. If I do I'll take a look at adding Blender support.

**Comment by j2l** [comment]
Thank you very much!
